name: rogzarpath
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.5
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  change_app_package_name: ^1.5.0
  intl: ^0.19.0
  share_plus: ^7.2.2
  flutter_widget_from_html: ^0.10.0
  carousel_slider: ^5.1.1
  percent_indicator: ^4.2.5
  fl_chart: ^0.60.0
  dio: ^5.8.0+1
  flutter_pdfview: ^1.3.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

# 👇 This ensures that flutter_math_fork works with your Flutter version

